In [46]:
# code to take adoption output and make the total counts into incremental counts

In [47]:
# read in pickle file
import pandas as pd
import numpy as np
baseline_results_df = pd.read_pickle("040_input/test/baseline_adoption_results.pkl")
tech_results_df = pd.read_pickle("040_input/test/tech_adoption_results.pkl")
competition_results_df = pd.read_pickle("040_input/test/competition_adoption_results.pkl")

In [48]:
tech_results_df

,competition_group,electric_utility,gas_utility,building_type,time,total_stock,total_below_baseline_stock,total_baseline_stock,total_efficient_stock,total_top10_stock,...,adoption_flow_efficient_nc,adoption_flow_top10_nc,adoption_flow_below_baseline_demo,adoption_flow_baseline_demo,adoption_flow_efficient_demo,adoption_flow_top10_demo,adoption_flow_below_baseline_reno,adoption_flow_baseline_reno,adoption_flow_efficient_reno,adoption_flow_top10_reno
0,refrigeration,test_utility_1,test_utility_1,single_family,0,132500.0,10000.000000,12500.000000,60000.000000,50000.000000,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,refrigeration,test_utility_1,test_utility_1,single_family,1,132500.0,8743.366337,10929.207921,52930.693069,59896.732673,...,0.0,1325.0,88.316832,110.396040,534.653465,591.633663,-88.316832,-110.396040,-534.653465,733.366337
2,refrigeration,test_utility_1,test_utility_1,single_family,2,132500.0,7552.947868,9441.184835,46117.831585,69388.035712,...,0.0,1325.0,76.292403,95.365503,465.836683,687.505411,-76.292403,-95.365503,-465.836683,637.494589
3,refrigeration,test_utility_1,test_utility_1,single_family,3,132500.0,6425.443140,8031.803925,39554.031298,78488.721638,...,0.0,1325.0,64.903466,81.129333,399.535670,779.431532,-64.903466,-81.129333,-399.535670,545.568468
4,refrigeration,test_utility_1,test_utility_1,single_family,4,132500.0,5357.716209,6697.145262,33232.099846,87213.038683,...,0.0,1325.0,54.118346,67.647932,335.677776,867.555946,-54.118346,-67.647932,-335.677776,457.444054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,refrigeration,test_utility_1,none,multifamily_li,15,22260.0,0.000000,0.000000,0.000000,22260.000000,...,0.0,222.6,0.000000,0.000000,0.000000,222.600000,0.000000,0.000000,0.000000,0.000000
236,refrigeration,test_utility_1,none,multifamily_li,16,22260.0,0.000000,0.000000,0.000000,22260.000000,...,0.0,222.6,0.000000,0.000000,0.000000,222.600000,0.000000,0.000000,0.000000,0.000000
237,refrigeration,test_utility_1,none,multifamily_li,17,22260.0,0.000000,0.000000,0.000000,22260.000000,...,0.0,222.6,0.000000,0.000000,0.000000,222.600000,0.000000,0.000000,0.000000,0.000000
238,refrigeration,test_utility_1,none,multifamily_li,18,22260.0,0.000000,0.000000,0.000000,22260.000000,...,0.0,222.6,0.000000,0.000000,0.000000,222.600000,0.000000,0.000000,0.000000,0.000000
239,refrigeration,test_utility_1,none,multifamily_li,19,22260.0,0.000000,0.000000,0.000000,22260.000000,...,0.0,222.6,0.000000,0.000000,0.000000,222.600000,0.000000,0.000000,0.000000,0.000000

In [49]:
# # Process all three dataframes in a loop
# # Step not needed any more as stock and flow happening on yearly bases
dataframes = {
    'baseline': baseline_results_df,
    'tech': tech_results_df,
    'competition': competition_results_df
}

In [50]:
# this code drops the columns with the string total_ from the dataframes list
for name, df in dataframes.items():
    cols_to_drop = [col for col in df.columns if 'total_' in col]
    if cols_to_drop:
        dataframes[name] = df.drop(columns=cols_to_drop)
        print(f"Dropped {len(cols_to_drop)} columns from {name}: {cols_to_drop}")
    else:
        print(f"No 'total_' columns found in {name}")

Dropped 5 columns from baseline: ['total_stock', 'total_below_baseline_stock', 'total_baseline_stock', 'total_efficient_stock', 'total_top10_stock']
Dropped 5 columns from tech: ['total_stock', 'total_below_baseline_stock', 'total_baseline_stock', 'total_efficient_stock', 'total_top10_stock']
Dropped 5 columns from competition: ['total_stock', 'total_below_baseline_stock', 'total_baseline_stock', 'total_efficient_stock', 'total_top10_stock']

In [51]:
# this code pivots the dataframes to make a Market column ret_er|rob|nc|demo|reno based on columns that start with adoption_flow and makes a column efficiency level (below_baseline|baseline|efficient|top10 based on the same set of columns. 
# there will be a new row created for each possible iteration of market and efficiency level combination
# 

import re

processed_dfs = {}

for name, df in dataframes.items():
    print(f"\nProcessing {name}_results_df...")
    
    # Find columns that start with adoption_flow
    flow_pattern = r'^adoption_flow_(below_baseline|baseline|efficient|top10)_(ret_er|rob|nc|demo|reno)$'
    flow_cols = [c for c in df.columns if c.startswith('adoption_flow_') and re.match(flow_pattern, c)]
    
    # Identify ID columns (everything that's not a flow column)
    id_cols = [c for c in df.columns if c not in flow_cols]
    
    print(f"Found {len(flow_cols)} adoption_flow columns")
    print(f"ID columns: {id_cols}")
    
    # Melt the dataframe to long format
    df_long = df.melt(
        id_vars=id_cols,
        value_vars=flow_cols,
        var_name='market_eff',
        value_name='adoption_flow'
    )
    
    # Extract market and efficiency_level from the column names
    df_long[['efficiency_level', 'market',]] = df_long['market_eff'].str.extract(flow_pattern)
    
    # Drop the intermediate column
    df_long = df_long.drop(columns=['market_eff'])
    
    print(f"Pivoted shape: {df_long.shape}")
    print(f"Sample of pivoted data:")
    display(df_long)
    
    processed_dfs[name] = df_long

print("\nAll dataframes processed successfully!")

Processing baseline_results_df...
Found 20 adoption_flow columns
ID columns: ['competition_group', 'electric_utility', 'gas_utility', 'building_type', 'time']
Pivoted shape: (4800, 8)
Sample of pivoted data:

,competition_group,electric_utility,gas_utility,building_type,time,adoption_flow,efficiency_level,market
0,refrigeration,test_utility_1,test_utility_1,single_family,0,0.0,below_baseline,rob
1,refrigeration,test_utility_1,test_utility_1,single_family,1,0.0,below_baseline,rob
2,refrigeration,test_utility_1,test_utility_1,single_family,2,0.0,below_baseline,rob
3,refrigeration,test_utility_1,test_utility_1,single_family,3,0.0,below_baseline,rob
4,refrigeration,test_utility_1,test_utility_1,single_family,4,0.0,below_baseline,rob
...,...,...,...,...,...,...,...,...
4795,refrigeration,test_utility_1,none,multifamily_li,15,0.0,top10,reno
4796,refrigeration,test_utility_1,none,multifamily_li,16,0.0,top10,reno
4797,refrigeration,test_utility_1,none,multifamily_li,17,0.0,top10,reno
4798,refrigeration,test_utility_1,none,multifamily_li,18,0.0,top10,reno
4799,refrigeration,test_utility_1,none,multifamily_li,19,0.0,top10,reno

Processing tech_results_df...
Found 20 adoption_flow columns
ID columns: ['competition_group', 'electric_utility', 'gas_utility', 'building_type', 'time']
Pivoted shape: (4800, 8)
Sample of pivoted data:
Pivoted shape: (4800, 8)
Sample of pivoted data:

,competition_group,electric_utility,gas_utility,building_type,time,adoption_flow,efficiency_level,market
0,refrigeration,test_utility_1,test_utility_1,single_family,0,0.0,below_baseline,rob
1,refrigeration,test_utility_1,test_utility_1,single_family,1,0.0,below_baseline,rob
2,refrigeration,test_utility_1,test_utility_1,single_family,2,0.0,below_baseline,rob
3,refrigeration,test_utility_1,test_utility_1,single_family,3,0.0,below_baseline,rob
4,refrigeration,test_utility_1,test_utility_1,single_family,4,0.0,below_baseline,rob
...,...,...,...,...,...,...,...,...
4795,refrigeration,test_utility_1,none,multifamily_li,15,0.0,top10,reno
4796,refrigeration,test_utility_1,none,multifamily_li,16,0.0,top10,reno
4797,refrigeration,test_utility_1,none,multifamily_li,17,0.0,top10,reno
4798,refrigeration,test_utility_1,none,multifamily_li,18,0.0,top10,reno
4799,refrigeration,test_utility_1,none,multifamily_li,19,0.0,top10,reno

Processing competition_results_df...
Found 20 adoption_flow columns
ID columns: ['competition_group', 'electric_utility', 'gas_utility', 'building_type', 'time']
Pivoted shape: (4800, 8)
Sample of pivoted data:

,competition_group,electric_utility,gas_utility,building_type,time,adoption_flow,efficiency_level,market
0,refrigeration,test_utility_1,test_utility_1,single_family,0,0.000000,below_baseline,rob
1,refrigeration,test_utility_1,test_utility_1,single_family,1,0.000000,below_baseline,rob
2,refrigeration,test_utility_1,test_utility_1,single_family,2,0.000000,below_baseline,rob
3,refrigeration,test_utility_1,test_utility_1,single_family,3,0.000000,below_baseline,rob
4,refrigeration,test_utility_1,test_utility_1,single_family,4,0.000000,below_baseline,rob
...,...,...,...,...,...,...,...,...
4795,refrigeration,test_utility_1,none,multifamily_li,15,1.052831,top10,reno
4796,refrigeration,test_utility_1,none,multifamily_li,16,1.060154,top10,reno
4797,refrigeration,test_utility_1,none,multifamily_li,17,1.065432,top10,reno
4798,refrigeration,test_utility_1,none,multifamily_li,18,1.068814,top10,reno
4799,refrigeration,test_utility_1,none,multifamily_li,19,1.070439,top10,reno

All dataframes processed successfully!

In [52]:
# this code now takes the time column and pivots the dataframes wider by appending the value in the time column to the adoption_flow column

reshaped_adoption_results = {}

for name, df in processed_dfs.items():
    print(f"\nReshaping {name}_results_df wider by time...")
    
    # Identify ID columns (everything except 'time' and 'adoption_flow')
    id_cols = [c for c in df.columns if c not in ['time', 'adoption_flow']]
    
    print(f"ID columns for grouping: {id_cols}")
    
    # Pivot wider: create columns like adoption_flow_2026, adoption_flow_2027, etc.
    df_wide = df.pivot_table(
        index=id_cols,
        columns='time',
        values='adoption_flow',
        aggfunc='first'
    ).reset_index()
    
    # Rename the time columns to adoption_flow_<time>
    df_wide.columns.name = None
    new_cols = []
    for col in df_wide.columns:
        if isinstance(col, (int, np.integer)):
            new_cols.append(f"adoption_flow_{col}")
        else:
            new_cols.append(col)
    df_wide.columns = new_cols
    
    print(f"Reshaped wide shape: {df_wide.shape}")
    print(f"New adoption_flow columns: {[c for c in df_wide.columns if c.startswith('adoption_flow_')]}")
    display(df_wide)
    
    reshaped_adoption_results[name] = df_wide

print("\nAll dataframes reshaped successfully!")

Reshaping baseline_results_df wider by time...
ID columns for grouping: ['competition_group', 'electric_utility', 'gas_utility', 'building_type', 'efficiency_level', 'market']
Reshaped wide shape: (240, 26)
New adoption_flow columns: ['adoption_flow_0', 'adoption_flow_1', 'adoption_flow_2', 'adoption_flow_3', 'adoption_flow_4', 'adoption_flow_5', 'adoption_flow_6', 'adoption_flow_7', 'adoption_flow_8', 'adoption_flow_9', 'adoption_flow_10', 'adoption_flow_11', 'adoption_flow_12', 'adoption_flow_13', 'adoption_flow_14', 'adoption_flow_15', 'adoption_flow_16', 'adoption_flow_17', 'adoption_flow_18', 'adoption_flow_19']

,competition_group,electric_utility,gas_utility,building_type,efficiency_level,market,adoption_flow_0,adoption_flow_1,adoption_flow_2,adoption_flow_3,...,adoption_flow_10,adoption_flow_11,adoption_flow_12,adoption_flow_13,adoption_flow_14,adoption_flow_15,adoption_flow_16,adoption_flow_17,adoption_flow_18,adoption_flow_19
0,refrigeration,test_utility_1,none,multifamily,baseline,demo,0.0,289.315248,445.191910,595.149125,...,1494.600000,1494.600000,1494.600000,1494.600000,1494.600000,1494.600000,1494.600000,1494.600000,1494.600000,1494.600000
1,refrigeration,test_utility_1,none,multifamily,baseline,nc,0.0,1494.600000,1494.600000,1494.600000,...,1494.600000,1494.600000,1494.600000,1494.600000,1494.600000,1494.600000,1494.600000,1494.600000,1494.600000,1494.600000
2,refrigeration,test_utility_1,none,multifamily,baseline,reno,0.0,1205.284752,1049.408090,899.450875,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,refrigeration,test_utility_1,none,multifamily,baseline,ret_er,0.0,203.040000,196.034115,190.240483,...,1179.029276,1156.457189,1135.255633,1120.233342,1110.805965,1106.429688,1105.971760,1129.837929,1147.685746,1160.151613
4,refrigeration,test_utility_1,none,multifamily,baseline,rob,0.0,14946.000000,14600.284752,14263.375988,...,12319.301695,13720.186191,13453.823134,13195.025887,12943.525896,12699.065725,12492.750445,12499.896408,12498.744652,12489.821535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,demo,0.0,178.217822,155.278894,133.178557,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
236,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,nc,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
237,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,reno,0.0,-178.217822,-155.278894,-133.178557,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
238,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,ret_er,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
239,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,rob,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

Reshaping tech_results_df wider by time...
ID columns for grouping: ['competition_group', 'electric_utility', 'gas_utility', 'building_type', 'efficiency_level', 'market']
Reshaped wide shape: (240, 26)
New adoption_flow columns: ['adoption_flow_0', 'adoption_flow_1', 'adoption_flow_2', 'adoption_flow_3', 'adoption_flow_4', 'adoption_flow_5', 'adoption_flow_6', 'adoption_flow_7', 'adoption_flow_8', 'adoption_flow_9', 'adoption_flow_10', 'adoption_flow_11', 'adoption_flow_12', 'adoption_flow_13', 'adoption_flow_14', 'adoption_flow_15', 'adoption_flow_16', 'adoption_flow_17', 'adoption_flow_18', 'adoption_flow_19']

,competition_group,electric_utility,gas_utility,building_type,efficiency_level,market,adoption_flow_0,adoption_flow_1,adoption_flow_2,adoption_flow_3,...,adoption_flow_10,adoption_flow_11,adoption_flow_12,adoption_flow_13,adoption_flow_14,adoption_flow_15,adoption_flow_16,adoption_flow_17,adoption_flow_18,adoption_flow_19
0,refrigeration,test_utility_1,none,multifamily,baseline,demo,0.0,124.526733,107.572288,91.513887,...,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
1,refrigeration,test_utility_1,none,multifamily,baseline,nc,0.0,0.000000,0.000000,0.000000,...,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
2,refrigeration,test_utility_1,none,multifamily,baseline,reno,0.0,-124.526733,-107.572288,-91.513887,...,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
3,refrigeration,test_utility_1,none,multifamily,baseline,ret_er,0.0,0.000000,0.000000,0.000000,...,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
4,refrigeration,test_utility_1,none,multifamily,baseline,rob,0.0,0.000000,0.000000,0.000000,...,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,demo,0.0,236.653465,275.002164,311.772613,...,530.0000,530.000000,530.000000,530.000000,530.000000,530.000000,530.000000,530.000000,530.00000,530.000000
236,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,nc,0.0,530.000000,530.000000,530.000000,...,530.0000,530.000000,530.000000,530.000000,530.000000,530.000000,530.000000,530.000000,530.00000,530.000000
237,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,reno,0.0,293.346535,254.997836,218.227387,...,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
238,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,ret_er,0.0,72.000000,69.515644,67.461164,...,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
239,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,rob,0.0,5300.000000,5177.405941,5057.934748,...,4368.5467,5274.807244,5172.402381,5072.906239,4976.215571,4882.231403,4802.912266,4712.093261,4623.58771,4537.329504

Reshaping competition_results_df wider by time...
ID columns for grouping: ['competition_group', 'electric_utility', 'gas_utility', 'building_type', 'efficiency_level', 'market']
Reshaped wide shape: (240, 26)
New adoption_flow columns: ['adoption_flow_0', 'adoption_flow_1', 'adoption_flow_2', 'adoption_flow_3', 'adoption_flow_4', 'adoption_flow_5', 'adoption_flow_6', 'adoption_flow_7', 'adoption_flow_8', 'adoption_flow_9', 'adoption_flow_10', 'adoption_flow_11', 'adoption_flow_12', 'adoption_flow_13', 'adoption_flow_14', 'adoption_flow_15', 'adoption_flow_16', 'adoption_flow_17', 'adoption_flow_18', 'adoption_flow_19']
Reshaped wide shape: (240, 26)
New adoption_flow columns: ['adoption_flow_0', 'adoption_flow_1', 'adoption_flow_2', 'adoption_flow_3', 'adoption_flow_4', 'adoption_flow_5', 'adoption_flow_6', 'adoption_flow_7', 'adoption_flow_8', 'adoption_flow_9', 'adoption_flow_10', 'adoption_flow_11', 'adoption_flow_12', 'adoption_flow_13', 'adoption_flow_14', 'adoption_flow_15', 'adoption_flow_16', 'adoption_flow_17', 'adoption_flow_18', 'adoption_flow_19']

,competition_group,electric_utility,gas_utility,building_type,efficiency_level,market,adoption_flow_0,adoption_flow_1,adoption_flow_2,adoption_flow_3,...,adoption_flow_10,adoption_flow_11,adoption_flow_12,adoption_flow_13,adoption_flow_14,adoption_flow_15,adoption_flow_16,adoption_flow_17,adoption_flow_18,adoption_flow_19
0,refrigeration,test_utility_1,none,multifamily,baseline,demo,0.0,1.245267e+02,107.572288,9.151389e+01,...,6.505532e-14,6.551124e-14,7.261674e-14,7.278135e-14,7.310242e-14,7.341085e-14,7.370712e-14,7.399172e-14,7.192439e-14,7.210271e-14
1,refrigeration,test_utility_1,none,multifamily,baseline,nc,0.0,0.000000e+00,0.000000,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2,refrigeration,test_utility_1,none,multifamily,baseline,reno,0.0,-1.245267e+02,-107.572288,-9.151389e+01,...,-6.505532e-14,-6.551124e-14,-7.261674e-14,-7.278135e-14,-7.310242e-14,-7.341085e-14,-7.370712e-14,-7.399172e-14,-7.192439e-14,-7.210271e-14
3,refrigeration,test_utility_1,none,multifamily,baseline,ret_er,0.0,0.000000e+00,0.000000,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
4,refrigeration,test_utility_1,none,multifamily,baseline,rob,0.0,9.094947e-13,0.000000,9.094947e-13,...,9.094947e-13,9.094947e-13,9.094947e-13,9.094947e-13,9.094947e-13,9.094947e-13,9.094947e-13,9.094947e-13,0.000000e+00,9.094947e-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,demo,0.0,2.067139e+02,213.685757,2.203176e+02,...,2.586285e+02,2.586095e+02,2.585913e+02,2.585741e+02,2.585575e+02,2.585416e+02,2.585262e+02,2.585152e+02,2.585081e+02,2.585047e+02
236,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,nc,0.0,2.608397e+02,260.839688,2.608397e+02,...,2.608397e+02,2.608397e+02,2.608397e+02,2.608397e+02,2.608397e+02,2.608397e+02,2.608397e+02,2.608397e+02,2.608397e+02,2.608397e+02
237,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,reno,0.0,5.412579e+01,47.153932,4.052211e+01,...,2.211156e+00,2.230228e+00,2.248349e+00,2.265637e+00,2.282199e+00,2.298132e+00,2.313455e+00,2.324501e+00,2.331577e+00,2.334977e+00
238,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,ret_er,0.0,3.710158e+01,35.821395,3.476272e+01,...,0.000000e+00,0.000000e+00,6.494759e-17,6.238827e-17,5.992980e-17,5.756821e-17,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
239,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,rob,0.0,2.580162e+03,2520.480797,2.462319e+03,...,2.126709e+03,2.567898e+03,2.518045e+03,2.469608e+03,2.422537e+03,2.376783e+03,2.338169e+03,2.293956e+03,2.250869e+03,2.208877e+03

All dataframes reshaped successfully!

In [53]:
#read in pickle file
# remember market is now an age thing not a replacement thing
df_yrs = pd.read_pickle("./030_input/df_yrs.pkl")
df_yrs
# filter df_years to remove any rows that have baseline or existing in the condition column
df_yrs = df_yrs[~df_yrs['condition'].str.contains('baseline|existing', case=False, na=False)]

# quickly make column efficiency_level based on the column condition_name. if condition_name contains 'efficient' then efficiency_level is 'efficient' else 'top10'
df_yrs['efficiency_level'] = np.where(df_yrs['condition'].str.contains('efficient', case=False, na=False), 'efficient', 'top10')

# Make 3 copies of the ROB market data and change market column to NC, DEMO, and RENO
df_rob = df_yrs[df_yrs['market'] == 'ROB'].copy()
print(f"Original ROB records: {len(df_rob)}")

# Create copies for NC, DEMO, and RENO
df_nc = df_rob.copy()
df_nc['market'] = 'NC'

df_demo = df_rob.copy()
df_demo['market'] = 'DEMO'

df_reno = df_rob.copy()
df_reno['market'] = 'RENO'

# Append these copies to df_yrs
df_yrs = pd.concat([df_yrs, df_nc, df_demo, df_reno], ignore_index=True)

print(f"After adding NC, DEMO, RENO: {len(df_yrs)} total records")
print(f"Market value counts:\n{df_yrs['market'].value_counts()}")

df_yrs

Original ROB records: 48
After adding NC, DEMO, RENO: 288 total records
Market value counts:
market
ROB          48
RET_ER       48
REMAINING    48
NC           48
DEMO         48
RENO         48
Name: count, dtype: int64

,condition,competition_group,subgroup,electric_utility,gas_utility,building_type,measure_life_(yrs),initial_count,market,count,...,SCT_cost,SCT_benefit,SCT_BCR,RIM_cost,RIM_benefit,RIM_BCR,PCT_cost,PCT_benefit,PCT_BCR,efficiency_level
0,furnace_oil_efficient_residential,heating_cooling,oil_furnace,test_utility_1,test_utility_1,single_family,10,5000.0,ROB,500.0,...,1680.0,3636.660007,2.164679,1172.716654,4138.658036,3.529120,700.0,4682.630596,6.689472,efficient
1,furnace_oil_efficient_residential,heating_cooling,oil_furnace,test_utility_1,test_utility_2,single_family,10,10000.0,ROB,1000.0,...,1680.0,3645.190210,2.169756,1172.716654,4138.658036,3.529120,700.0,4691.160799,6.701658,efficient
2,furnace_oil_efficient_residential,heating_cooling,oil_furnace,test_utility_1,none,single_family,10,27500.0,ROB,2750.0,...,1680.0,3636.660007,2.164679,1172.716654,4138.658036,3.529120,700.0,4682.630596,6.689472,efficient
3,furnace_natural_gas_efficient_residential,heating_cooling,gas_furnace,test_utility_1,test_utility_1,single_family,10,5000.0,ROB,500.0,...,1680.0,3636.660007,2.164679,1172.716654,4138.658036,3.529120,700.0,4682.630596,6.689472,efficient
4,furnace_natural_gas_efficient_residential,heating_cooling,gas_furnace,test_utility_1,test_utility_2,single_family,10,10000.0,ROB,1000.0,...,1680.0,3645.190210,2.169756,1172.716654,4138.658036,3.529120,700.0,4691.160799,6.701658,efficient
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,refrigerator_electricity_efficient_residential,refrigeration,full_size,test_utility_1,test_utility_2,multifamily_li,10,3600.0,RENO,360.0,...,1080.0,3170.657706,2.935794,2037.916338,2443.699971,1.199117,450.0,4086.402419,9.080894,efficient
284,refrigerator_electricity_efficient_residential,refrigeration,full_size,test_utility_1,none,multifamily_li,10,2520.0,RENO,252.0,...,1080.0,3162.127503,2.927896,2037.916338,2443.699971,1.199117,450.0,4077.872216,9.061938,efficient
285,refrigerator_electricity_top10_residential,refrigeration,full_size,test_utility_1,test_utility_1,multifamily_li,10,750.0,RENO,75.0,...,1800.0,4919.156168,2.732865,3250.092082,3841.311067,1.181908,750.0,6417.659055,8.556879,top10
286,refrigerator_electricity_top10_residential,refrigeration,full_size,test_utility_1,test_utility_2,multifamily_li,10,3000.0,RENO,300.0,...,1800.0,4927.686371,2.737604,3250.092082,3841.311067,1.181908,750.0,6426.189257,8.568252,top10
287,refrigerator_electricity_top10_residential,refrigeration,full_size,test_utility_1,none,multifamily_li,10,2100.0,RENO,210.0,...,1800.0,4919.156168,2.732865,3250.092082,3841.311067,1.181908,750.0,6417.659055,8.556879,top10

In [54]:
# Now join the reshaped adoption results with the avoided cost data from df_yrs
# The join will match on: competition_group, electric_utility, gas_utility, building_type, efficiency_level, market

joined_results = {}

for name in reshaped_adoption_results.keys():
    df_reshaped = reshaped_adoption_results[name].copy()

    df_reshaped['market'] = df_reshaped['market'].str.upper()
    
    print(f"\n{name.capitalize()} market values after standardization: {df_reshaped['market'].unique()}")
    
    # Now join with df_yrs to get avoided costs
    # Get relevant columns from df_yrs (exclude time-based adoption columns, keep cost/benefit columns)
    cost_benefit_cols = [col for col in df_yrs.columns if not col.startswith('adopt_t_') and not col.startswith('adoption_flow_')]
    df_yrs_costs = df_yrs[cost_benefit_cols].drop_duplicates()
    
    # FIX 2: Filter df_yrs_costs to only include markets that exist in reshaped data (ROB and RET_ER)
    df_yrs_costs = df_yrs_costs[df_yrs_costs['market'].isin(df_reshaped['market'].unique())]
    
    print(f"   df_yrs_costs shape after filtering: {df_yrs_costs.shape}")
    print(f"   df_yrs_costs markets: {df_yrs_costs['market'].unique()}")
    
    # Perform the join
    df_joined = df_reshaped.merge(
        df_yrs_costs,
        on=['competition_group', 'electric_utility', 'gas_utility', 'building_type', 'efficiency_level', 'market'],
        how='left'
    )
    
    joined_results[name] = df_joined
    print(f"\n{name.capitalize()} joined with costs shape: {df_joined.shape}")
    
    # Check for any null values in key cost columns to verify join success
    sample_cost_cols = [col for col in df_joined.columns if 'cost' in col.lower() or 'benefit' in col.lower()][:5]
    if sample_cost_cols:
        null_counts = df_joined[sample_cost_cols].isnull().sum()
        print(f"   Null counts in sample cost columns:\n{null_counts}")
    
    display(df_joined)

# Store for later use
print("\n" + "="*80)
print("Join completed successfully!")

Baseline market values after standardization: ['DEMO' 'NC' 'RENO' 'RET_ER' 'ROB']
   df_yrs_costs shape after filtering: (240, 110)
   df_yrs_costs markets: ['ROB' 'RET_ER' 'NC' 'DEMO' 'RENO']

Baseline joined with costs shape: (240, 130)
   Null counts in sample cost columns:
incremental_cost_(usd)                          120
measure_incremental_cost                        120
electric_utility_nonmeasure_program_cost        120
natural_gas_utility_nonmeasure_program_costs    120
nonutility_nonmeasure_program_costs             120
dtype: int64

,competition_group,electric_utility,gas_utility,building_type,efficiency_level,market,adoption_flow_0,adoption_flow_1,adoption_flow_2,adoption_flow_3,...,TRC_BCR,SCT_cost,SCT_benefit,SCT_BCR,RIM_cost,RIM_benefit,RIM_BCR,PCT_cost,PCT_benefit,PCT_BCR
0,refrigeration,test_utility_1,none,multifamily,baseline,DEMO,0.0,289.315248,445.191910,595.149125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,refrigeration,test_utility_1,none,multifamily,baseline,NC,0.0,1494.600000,1494.600000,1494.600000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,refrigeration,test_utility_1,none,multifamily,baseline,RENO,0.0,1205.284752,1049.408090,899.450875,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,refrigeration,test_utility_1,none,multifamily,baseline,RET_ER,0.0,203.040000,196.034115,190.240483,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,refrigeration,test_utility_1,none,multifamily,baseline,ROB,0.0,14946.000000,14600.284752,14263.375988,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,DEMO,0.0,178.217822,155.278894,133.178557,...,1.094218,1800.0,2966.534266,1.648075,2430.055249,2544.786640,1.047213,750.0,4309.627998,5.746171
236,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,NC,0.0,0.000000,0.000000,0.000000,...,1.094218,1800.0,2966.534266,1.648075,2430.055249,2544.786640,1.047213,750.0,4309.627998,5.746171
237,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,RENO,0.0,-178.217822,-155.278894,-133.178557,...,1.094218,1800.0,2966.534266,1.648075,2430.055249,2544.786640,1.047213,750.0,4309.627998,5.746171
238,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,RET_ER,0.0,0.000000,0.000000,0.000000,...,0.698219,3840.0,4034.151465,1.050560,4229.360695,3919.353297,0.926701,1600.0,6718.500101,4.199063
239,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,ROB,0.0,0.000000,0.000000,0.000000,...,1.094218,1800.0,2966.534266,1.648075,2430.055249,2544.786640,1.047213,750.0,4309.627998,5.746171

Tech market values after standardization: ['DEMO' 'NC' 'RENO' 'RET_ER' 'ROB']
   df_yrs_costs shape after filtering: (240, 110)
   df_yrs_costs markets: ['ROB' 'RET_ER' 'NC' 'DEMO' 'RENO']

Tech joined with costs shape: (240, 130)
   Null counts in sample cost columns:
incremental_cost_(usd)                          120
measure_incremental_cost                        120
electric_utility_nonmeasure_program_cost        120
natural_gas_utility_nonmeasure_program_costs    120
nonutility_nonmeasure_program_costs             120
dtype: int64

,competition_group,electric_utility,gas_utility,building_type,efficiency_level,market,adoption_flow_0,adoption_flow_1,adoption_flow_2,adoption_flow_3,...,TRC_BCR,SCT_cost,SCT_benefit,SCT_BCR,RIM_cost,RIM_benefit,RIM_BCR,PCT_cost,PCT_benefit,PCT_BCR
0,refrigeration,test_utility_1,none,multifamily,baseline,DEMO,0.0,124.526733,107.572288,91.513887,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,refrigeration,test_utility_1,none,multifamily,baseline,NC,0.0,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,refrigeration,test_utility_1,none,multifamily,baseline,RENO,0.0,-124.526733,-107.572288,-91.513887,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,refrigeration,test_utility_1,none,multifamily,baseline,RET_ER,0.0,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,refrigeration,test_utility_1,none,multifamily,baseline,ROB,0.0,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,DEMO,0.0,236.653465,275.002164,311.772613,...,1.094218,1800.0,2966.534266,1.648075,2430.055249,2544.786640,1.047213,750.0,4309.627998,5.746171
236,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,NC,0.0,530.000000,530.000000,530.000000,...,1.094218,1800.0,2966.534266,1.648075,2430.055249,2544.786640,1.047213,750.0,4309.627998,5.746171
237,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,RENO,0.0,293.346535,254.997836,218.227387,...,1.094218,1800.0,2966.534266,1.648075,2430.055249,2544.786640,1.047213,750.0,4309.627998,5.746171
238,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,RET_ER,0.0,72.000000,69.515644,67.461164,...,0.698219,3840.0,4034.151465,1.050560,4229.360695,3919.353297,0.926701,1600.0,6718.500101,4.199063
239,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,ROB,0.0,5300.000000,5177.405941,5057.934748,...,1.094218,1800.0,2966.534266,1.648075,2430.055249,2544.786640,1.047213,750.0,4309.627998,5.746171

Competition market values after standardization: ['DEMO' 'NC' 'RENO' 'RET_ER' 'ROB']
   df_yrs_costs shape after filtering: (240, 110)
   df_yrs_costs markets: ['ROB' 'RET_ER' 'NC' 'DEMO' 'RENO']

Competition joined with costs shape: (240, 130)
   Null counts in sample cost columns:
incremental_cost_(usd)                          120
measure_incremental_cost                        120
electric_utility_nonmeasure_program_cost        120
natural_gas_utility_nonmeasure_program_costs    120
nonutility_nonmeasure_program_costs             120
dtype: int64

,competition_group,electric_utility,gas_utility,building_type,efficiency_level,market,adoption_flow_0,adoption_flow_1,adoption_flow_2,adoption_flow_3,...,TRC_BCR,SCT_cost,SCT_benefit,SCT_BCR,RIM_cost,RIM_benefit,RIM_BCR,PCT_cost,PCT_benefit,PCT_BCR
0,refrigeration,test_utility_1,none,multifamily,baseline,DEMO,0.0,1.245267e+02,107.572288,9.151389e+01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,refrigeration,test_utility_1,none,multifamily,baseline,NC,0.0,0.000000e+00,0.000000,0.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,refrigeration,test_utility_1,none,multifamily,baseline,RENO,0.0,-1.245267e+02,-107.572288,-9.151389e+01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,refrigeration,test_utility_1,none,multifamily,baseline,RET_ER,0.0,0.000000e+00,0.000000,0.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,refrigeration,test_utility_1,none,multifamily,baseline,ROB,0.0,9.094947e-13,0.000000,9.094947e-13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,DEMO,0.0,2.067139e+02,213.685757,2.203176e+02,...,1.094218,1800.0,2966.534266,1.648075,2430.055249,2544.786640,1.047213,750.0,4309.627998,5.746171
236,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,NC,0.0,2.608397e+02,260.839688,2.608397e+02,...,1.094218,1800.0,2966.534266,1.648075,2430.055249,2544.786640,1.047213,750.0,4309.627998,5.746171
237,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,RENO,0.0,5.412579e+01,47.153932,4.052211e+01,...,1.094218,1800.0,2966.534266,1.648075,2430.055249,2544.786640,1.047213,750.0,4309.627998,5.746171
238,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,RET_ER,0.0,3.710158e+01,35.821395,3.476272e+01,...,0.698219,3840.0,4034.151465,1.050560,4229.360695,3919.353297,0.926701,1600.0,6718.500101,4.199063
239,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,ROB,0.0,2.580162e+03,2520.480797,2.462319e+03,...,1.094218,1800.0,2966.534266,1.648075,2430.055249,2544.786640,1.047213,750.0,4309.627998,5.746171

================================================================================
Join completed successfully!

In [55]:
# now this code will multiply each adoption_flow_## column by the costs columns
# measure_incremental_cost	demand_ratio	deferred_replacement_credit_value	measure_water_savings	measure_electric_energy_savings	measure_natural_gas_savings	measure_fuel_oil_savings	measure_propane_savings	measure_gasoline_savings	measure_diesel_savings	electric_energy_savings_value	electric_demand_savings_value	natural_gas_savings_value	fuel_oil_savings_value	propane_savings_value	diesel_transportation_savings_value	gasoline_transportation_savings_value	other_fuel_savings_value	annual_oandm_savings	o_and_m_savings_value	water_savings_value	electric_incentive_pct	natural_gas_incentive_pct	nonutility_incentive_pct	electric_utility_incentive_value	natural_gas_utility_incentive_value	nonutility_incentive_value	total_incentive_value	electric_utility_nonmeasure_program_cost	natural_gas_utility_nonmeasure_program_costs	nonutility_nonmeasure_program_costs	risk_discount_value	electric_carbon_savings_value	electric_n2o_savings_value	electric_ch4_savings_value	natural_gas_carbon_savings_value	fuel_oil_carbon_savings_value	propane_carbon_savings_value	diesel_transportation_carbon_savings_value	gasoline_transportation_carbon_savings_value	natural_gas_n2o_savings_value	fuel_oil_n2o_savings_value	propane_n2o_savings_value	diesel_transportation_n2o_savings_value	gasoline_transportation_n2o_savings_value	natural_gas_ch4_savings_value	fuel_oil_ch4_savings_value	propane_ch4_savings_value	diesel_transportation_ch4_savings_value	gasoline_transportation_ch4_savings_value	end_use_fuel_externalities	other_nonresource_benefits	electric_customer_bill_savings	natural_gas_customer_bill_savings	heating_oil_customer_bill_savings	EUCT_cost	EUCT_benefit		GUCT_cost	GUCT_benefit		EGUCT_cost	EGUCT_benefit		TRC_cost	TRC_benefit		SCT_cost	SCT_benefit		RIM_cost	RIM_benefit		PCT_cost	PCT_benefit	
# the results will be new columns with the _## from the adoption_flow_## column appended on to the name of the other column 
# measure_incremental_cost_1 for when it was multipled by adoption_flow_1 

# Define the cost/benefit columns to multiply
cost_benefit_columns = [
    'measure_incremental_cost', 'deferred_replacement_credit_value',
    'measure_water_savings', 'measure_electric_energy_savings', 'measure_natural_gas_savings',
    'measure_fuel_oil_savings', 'measure_propane_savings', 'measure_gasoline_savings',
    'measure_diesel_savings', 'electric_energy_savings_value', 'electric_demand_savings_value',
    'natural_gas_savings_value', 'fuel_oil_savings_value', 'propane_savings_value',
    'diesel_transportation_savings_value', 'gasoline_transportation_savings_value',
    'other_fuel_savings_value', 'annual_oandm_savings', 'o_and_m_savings_value',
    'water_savings_value', 'electric_incentive_pct', 'natural_gas_incentive_pct',
    'nonutility_incentive_pct', 'electric_utility_incentive_value',
    'natural_gas_utility_incentive_value', 'nonutility_incentive_value',
    'total_incentive_value', 'electric_utility_nonmeasure_program_cost',
    'natural_gas_utility_nonmeasure_program_costs', 'nonutility_nonmeasure_program_costs',
    'risk_discount_value', 'electric_carbon_savings_value', 'electric_n2o_savings_value',
    'electric_ch4_savings_value', 'natural_gas_carbon_savings_value',
    'fuel_oil_carbon_savings_value', 'propane_carbon_savings_value',
    'diesel_transportation_carbon_savings_value', 'gasoline_transportation_carbon_savings_value',
    'natural_gas_n2o_savings_value', 'fuel_oil_n2o_savings_value',
    'propane_n2o_savings_value', 'diesel_transportation_n2o_savings_value',
    'gasoline_transportation_n2o_savings_value', 'natural_gas_ch4_savings_value',
    'fuel_oil_ch4_savings_value', 'propane_ch4_savings_value',
    'diesel_transportation_ch4_savings_value', 'gasoline_transportation_ch4_savings_value',
    'end_use_fuel_externalities', 'other_nonresource_benefits',
    'electric_customer_bill_savings', 'natural_gas_customer_bill_savings',
    'heating_oil_customer_bill_savings', 'EUCT_cost', 'EUCT_benefit',
    'GUCT_cost', 'GUCT_benefit', 'EGUCT_cost', 'EGUCT_benefit',
    'TRC_cost', 'TRC_benefit', 'SCT_cost', 'SCT_benefit',
    'RIM_cost', 'RIM_benefit', 'PCT_cost', 'PCT_benefit'
]

final_dollar_results = {}

for name, df in joined_results.items():
    print(f"\nProcessing {name} for dollar calculations...")
    
    df_result = df.copy()
    
    # Find all adoption_flow columns
    adoption_flow_cols = [col for col in df.columns if col.startswith('adoption_flow_')]
    print(f"Found {len(adoption_flow_cols)} adoption_flow columns")
    
    # For each adoption_flow column, multiply by each cost/benefit column
    for flow_col in adoption_flow_cols:
        # Extract the year/time suffix (e.g., "2026" from "adoption_flow_2026")
        year_suffix = flow_col.replace('adoption_flow_', '')
        
        for cost_col in cost_benefit_columns:
            # Check if the cost column exists in the dataframe
            if cost_col in df.columns:
                # Create new column name (e.g., "measure_incremental_cost_2026")
                new_col_name = f"{cost_col}_{year_suffix}"
                
                # Multiply adoption flow by cost/benefit value
                df_result[new_col_name] = df[flow_col] * df[cost_col]
    
    # Get the newly created columns
    new_cols = [col for col in df_result.columns if any(col.startswith(f"{c}_") for c in cost_benefit_columns)]
    print(f"Created {len(new_cols)} new dollar-value columns")
    
    final_dollar_results[name] = df_result
    
    print(f"Final shape for {name}: {df_result.shape}")
    display(df_result)

print("\nDollar calculations completed for all scenarios!")

Processing baseline for dollar calculations...
Found 20 adoption_flow columns

C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]

C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]

Created 1361 new dollar-value columns
Final shape for baseline: (240, 1490)

C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]

,competition_group,electric_utility,gas_utility,building_type,efficiency_level,market,adoption_flow_0,adoption_flow_1,adoption_flow_2,adoption_flow_3,...,EGUCT_cost_19,EGUCT_benefit_19,TRC_cost_19,TRC_benefit_19,SCT_cost_19,SCT_benefit_19,RIM_cost_19,RIM_benefit_19,PCT_cost_19,PCT_benefit_19
0,refrigeration,test_utility_1,none,multifamily,baseline,DEMO,0.0,289.315248,445.191910,595.149125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,refrigeration,test_utility_1,none,multifamily,baseline,NC,0.0,1494.600000,1494.600000,1494.600000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,refrigeration,test_utility_1,none,multifamily,baseline,RENO,0.0,1205.284752,1049.408090,899.450875,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,refrigeration,test_utility_1,none,multifamily,baseline,RET_ER,0.0,203.040000,196.034115,190.240483,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,refrigeration,test_utility_1,none,multifamily,baseline,ROB,0.0,14946.000000,14600.284752,14263.375988,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,DEMO,0.0,178.217822,155.278894,133.178557,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
236,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,NC,0.0,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
237,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,RENO,0.0,-178.217822,-155.278894,-133.178557,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
238,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,RET_ER,0.0,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
239,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,ROB,0.0,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Processing tech for dollar calculations...
Found 20 adoption_flow columns

C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]

Created 1361 new dollar-value columns
Final shape for tech: (240, 1490)

,competition_group,electric_utility,gas_utility,building_type,efficiency_level,market,adoption_flow_0,adoption_flow_1,adoption_flow_2,adoption_flow_3,...,EGUCT_cost_19,EGUCT_benefit_19,TRC_cost_19,TRC_benefit_19,SCT_cost_19,SCT_benefit_19,RIM_cost_19,RIM_benefit_19,PCT_cost_19,PCT_benefit_19
0,refrigeration,test_utility_1,none,multifamily,baseline,DEMO,0.0,124.526733,107.572288,91.513887,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,refrigeration,test_utility_1,none,multifamily,baseline,NC,0.0,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,refrigeration,test_utility_1,none,multifamily,baseline,RENO,0.0,-124.526733,-107.572288,-91.513887,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,refrigeration,test_utility_1,none,multifamily,baseline,RET_ER,0.0,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,refrigeration,test_utility_1,none,multifamily,baseline,ROB,0.0,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,DEMO,0.0,236.653465,275.002164,311.772613,...,6.360000e+05,1.030737e+06,9.540000e+05,1.043884e+06,9.540000e+05,1.572263e+06,1.287929e+06,1.348737e+06,3.975000e+05,2.284103e+06
236,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,NC,0.0,530.000000,530.000000,530.000000,...,6.360000e+05,1.030737e+06,9.540000e+05,1.043884e+06,9.540000e+05,1.572263e+06,1.287929e+06,1.348737e+06,3.975000e+05,2.284103e+06
237,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,RENO,0.0,293.346535,254.997836,218.227387,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
238,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,RET_ER,0.0,72.000000,69.515644,67.461164,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
239,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,ROB,0.0,5300.000000,5177.405941,5057.934748,...,5.444795e+06,8.824138e+06,8.167193e+06,8.936691e+06,8.167193e+06,1.346014e+07,1.102596e+07,1.154654e+07,3.402997e+06,1.955420e+07

Processing competition for dollar calculations...
Found 20 adoption_flow columns

C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]
C:\Users\AndrewJ.Johnson\AppData\Local\Temp\ipykernel_20820\1087741154.py:60: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_result[new_col_name] = df[flow_col] * df[cost_col]

Created 1361 new dollar-value columns
Final shape for competition: (240, 1490)

,competition_group,electric_utility,gas_utility,building_type,efficiency_level,market,adoption_flow_0,adoption_flow_1,adoption_flow_2,adoption_flow_3,...,EGUCT_cost_19,EGUCT_benefit_19,TRC_cost_19,TRC_benefit_19,SCT_cost_19,SCT_benefit_19,RIM_cost_19,RIM_benefit_19,PCT_cost_19,PCT_benefit_19
0,refrigeration,test_utility_1,none,multifamily,baseline,DEMO,0.0,1.245267e+02,107.572288,9.151389e+01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,refrigeration,test_utility_1,none,multifamily,baseline,NC,0.0,0.000000e+00,0.000000,0.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,refrigeration,test_utility_1,none,multifamily,baseline,RENO,0.0,-1.245267e+02,-107.572288,-9.151389e+01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,refrigeration,test_utility_1,none,multifamily,baseline,RET_ER,0.0,0.000000e+00,0.000000,0.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,refrigeration,test_utility_1,none,multifamily,baseline,ROB,0.0,9.094947e-13,0.000000,9.094947e-13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,DEMO,0.0,2.067139e+02,213.685757,2.203176e+02,...,3.102057e+05,5.027365e+05,4.653085e+05,5.091490e+05,4.653085e+05,7.668631e+05,6.281807e+05,6.578393e+05,1.938785e+05,1.114059e+06
236,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,NC,0.0,2.608397e+02,260.839688,2.608397e+02,...,3.130076e+05,5.072775e+05,4.695114e+05,5.137480e+05,4.695114e+05,7.737899e+05,6.338549e+05,6.637814e+05,1.956298e+05,1.124122e+06
237,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,RENO,0.0,5.412579e+01,47.153932,4.052211e+01,...,2.801972e+03,4.541032e+03,4.202958e+03,4.598954e+03,4.202958e+03,6.926789e+03,5.674123e+03,5.942018e+03,1.751233e+03,1.006288e+04
238,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,RET_ER,0.0,3.710158e+01,35.821395,3.476272e+01,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
239,refrigeration,test_utility_1,test_utility_2,single_family_li,top10,ROB,0.0,2.580162e+03,2520.480797,2.462319e+03,...,2.650652e+06,4.295794e+06,3.975978e+06,4.350588e+06,3.975978e+06,6.552709e+06,5.367693e+06,5.621120e+06,1.656658e+06,9.519437e+06

Dollar calculations completed for all scenarios!

###

In [59]:
# Save all processed dataframes to pickle and CSV files
for name, df in final_dollar_results.items():
    output_pkl = f"040_output/{name}_final_dollar_results.pkl"
    output_csv = f"040_output/{name}_final_dollar_results.csv"
    df.to_pickle(output_pkl)
    df.to_csv(output_csv, index=False)
    print(f"Saved {name} results to {output_pkl} and {output_csv}")

for name, df in final_dollar_results.items():
    output_pkl = f"050_input/{name}_final_dollar_results.pkl"
    output_csv = f"050_input/{name}_final_dollar_results.csv"
    df.to_pickle(output_pkl)
    df.to_csv(output_csv, index=False)
    print(f"Saved {name} results to {output_pkl} and {output_csv}")

Saved baseline results to 040_output/baseline_final_dollar_results.pkl and 040_output/baseline_final_dollar_results.csv
Saved tech results to 040_output/tech_final_dollar_results.pkl and 040_output/tech_final_dollar_results.csv
Saved tech results to 040_output/tech_final_dollar_results.pkl and 040_output/tech_final_dollar_results.csv
Saved competition results to 040_output/competition_final_dollar_results.pkl and 040_output/competition_final_dollar_results.csv
Saved competition results to 040_output/competition_final_dollar_results.pkl and 040_output/competition_final_dollar_results.csv

OSError: Cannot save file into a non-existent directory: '050_input'